---
# Handlers for Jaeger
- name: Restart jaeger
  community.docker.docker_container:
    name: jaeger
    state: started
    restart: true

- name: Restart nginx
  systemd_service:
    name: nginx
    state: restarted
