---
- name: Creating document root
  file:
    path: /var/www/{{ _domain }}/public_html
    owner: www-data
    group: www-data
    mode: '0755'
    state: directory
  register: document_root

- name: Move index.html template
  copy:
    src: files/index.html
    dest: "{{ document_root.path }}/index.html"
    owner: www-data
    group: www-data
    mode: '0644'

- name: Moving vhost template
  template:
    src: templates/vhost.conf.j2
    dest: "/etc/apache2/sites-available/{{ _domain }}.conf"
    owner: root
    group: root
    mode: '0644'

- name: Symlinking our vhost
  file:
    src: "/etc/apache2/sites-available/{{ _domain }}.conf"
    dest: "/etc/apache2/sites-enabled/{{ _domain }}.conf"
    owner: root
    group: root
    mode: '0644'
    state: link
  notify: Reload apache2
