---
# apache
- name: Installing apache
  apt:
    pkg:
      - apache2
    state: present

- name: Enabling apache on boot
  service:
    name: apache2
    enabled: true

- name: Enable apache rewrite module
  apache2_module:
    name: rewrite
    state: present
  notify: Reload apache2

- name: Disable apache default site
  file:
    path: /etc/apache2/sites-enabled/000-default.conf
    state: absent

- name: Apache configs for customer domain
  import_tasks: apache_configs.yml

# mysql
- name: Installing mariadb
  apt:
    pkg:
      - mariadb-server
      - python3-mysqldb
    state: present
  register: mariadb

- name: Running mysql secure installation
  import_role:
    name: securemysql

# php
- name: Install php
  apt:
    pkg:
      - php-common
      - libapache2-mod-php
      - php-mysql
    state: present

- name: Configuring domain with certbot
  import_role:
    name: certbot_ssl
