---

# Simplex service/docker setup

- name: Simplex setup
  block:
    - name: Setup systemd service
      template:
        src: simplex.service
        dest: /etc/systemd/system/simplex.service
        mode: '0644'
    - name: Create docker compose directory
      file:
        path: /etc/docker/compose/simplex
        state: directory
        mode: '0755'
    - name: Create persistent directories
      file:
        path: "{{ item }}"
        state: directory
        mode: '0755'
      loop:
        - /etc/opt/simplex
        - /var/opt/simplex
        - /etc/opt/simplex-xftp
        - /var/opt/simplex-xftp
        - /srv/xftp
    - name: Setup docker compose
      template:
        src: docker-compose.yaml
        dest: /etc/docker/compose/simplex/docker-compose.yml
        mode: '0644'
    - name: Reload systemd daemon
      systemd:
        daemon_reload: true
    - name: Enable Simplex Service
      systemd:
        name: simplex.service
        enabled: true
    - name: Start Simplex Service
      systemd:
        name: simplex.service
        state: started
