---
# remove test nvm env vars and package.json
- name: Removing env vars and package.json
  file:
    path: '{{ item }}'
    state: absent
  loop:
    - '{{ backstage_username_directory }}/.nvmvars'
    - '{{ backstage_username_directory }}/package.json'
