---
# update postgresql access
- name: Update postgres password
  postgresql_query:
    db: postgres
    query: "ALTER USER postgres PASSWORD '{{ postgres_password }}';"
  become: true
  become_method: ansible.builtin.su
  become_user: postgres
