---
# set_hostname
- name: setting up hostname
  import_role:
    name: hostname

# write _domain to vars.
- name: write _domain to vars
  lineinfile: 
    insertafter: EOF
    path: group_vars/linode/vars
    line: | 
      _domain: {{ _domain }}
  when: _domain is defined 

# sets customer supplied ssh pubkey to limited user
- name: set ssh pubkey
  import_role:
    name: sshkey

# disable root login w/wo pubkey
- name: secure ssh
  import_role:
      name: securessh
  when: disable_root is defined

# apt_setup_update
- name: update system packages
  import_role:
    name: update_pkgs

# ufw_install
- name: enabling ufw
  import_role:
    name: ufw

# ufw rules 
- name: apply ufw rules
  import_tasks: ufw_rules.yml

# fail2ban
- name: enabling fail2ban
  import_role:
    name: fail2ban_install