---
# Install Addons if requested
- name: Add addons
  import_role:
    name: addons
  when: add_ons != ['none']

# certbot is installed to venv w/ pip in deploy.sh

- name: Run certbot dry-run
  shell:
    cmd: "certbot certonly -n --standalone --dry-run --agree-tos -d {{ _domain }} -m {{ soa_email_address }}"
  run_once: true
  register: dry_run
  until: dry_run is not failed
  retries: 3
  delay: 3
  ignore_errors: true

- name: Validate certbot dry-run
  assert:
    that: dry_run is not failed
    fail_msg: "[Error] Certbot dry-run failed. Cannot continue..Check the domain provided"
    success_msg: "[Info] Certbot dry-run successful!"
  run_once: true

# issue cert
- name: Run certbot
  shell:
    cmd: "certbot certonly -n --standalone --agree-tos -d {{ _domain }} -m {{ soa_email_address }}"

- name: Use openvpn ssl key scripts
  ansible.builtin.shell:
    executable: /bin/bash
    chdir: /usr/local/openvpn_as/scripts
    cmd: "./sacli --key cs.priv_key --value_file /etc/letsencrypt/live/{{ _domain }}/privkey.pem ConfigPut"

- name: Use openvpn ssl cert scripts
  shell:
    executable: /bin/bash
    chdir: /usr/local/openvpn_as/scripts
    cmd: "./sacli --key cs.cert --value_file /etc/letsencrypt/live/{{ _domain }}/fullchain.pem ConfigPut"
  notify: Restart openvpn

- name: Capture OpenVPN creds
  ansible.builtin.slurp:
    src: /usr/local/openvpn_as/init.log
  register: openvpn_log

- name: Regex for generated password
  ansible.builtin.debug:
    msg: >-
      {{ openvpn_log.content | b64decode
      | regex_search('Auto-generated pass = \"([^\"]+)\"', multiline=True)
      | regex_search('\"([^\"]+)\"')
      | regex_replace('[\"\\\\]', '') }}
  register: openvpn_pass

# motd and creds gen
- name: Copy MOTD template to /etc/motd
  template:
    src: templates/motd.j2
    dest: /etc/motd
    mode: '0600'
    owner: '{{ username }}'
    group: '{{ username }}'

- name: Writing sudo creds into file
  copy:
    dest: '/home/{{ username }}/.credentials'
    mode: '0600'
    owner: '{{ username }}'
    group: '{{ username }}'
    content: |
      Sudo Username: {{ username }}
      Sudo Password: {{ password }}
      OpenVPN Username: openvpn
      OpenVPN Password: {{ openvpn_pass.msg }}
