---
# database
- name: Install mariadb helper
  import_role:
    name: database
  vars:
    database: "mariadb"

- name: Create moodle database
  mysql_db:
    name: moodle
    state: present
    login_user: root
    login_unix_socket: /var/run/mysqld/mysqld.sock

- name: Create moodle db user
  mysql_user:
    name: "{{ db_user }}"
    password: "{{ db_user_password }}"
    priv: "moodle.*:ALL"
    host: "localhost"
    state: present
    login_user: root
    login_unix_socket: /var/run/mysqld/mysqld.sock
