---
- name: Install redis
  import_role:
    name: database
  vars:
    database: redis

- name: Create backup of redis configurations
  copy:
    src: /etc/redis/redis.conf
    dest: /etc/redis/redis.conf.bak
    remote_src: true
    owner: redis
    group: redis
    mode: '0644'

- name: Template modified config file
  template:
    src: 'templates/redis.conf.j2'
    dest: '{{ redis_conf_directory }}/redis.conf'
    owner: redis
    group: redis
    mode: '0644'
  notify: Restart redis
