---
- name: Generate MySQL root password
  set_fact:
    mysql_root_password: "{{ lookup('password', '/etc/ansible/mysql_root_password length=45 chars=ascii_letters,digits') }}"

- name: Install MariaDB
  apt:
    pkg:
      - mariadb-server
      - python3-mysqldb
    state: present
    update_cache: yes

- name: Ensure MySQL service is started
  service:
    name: mariadb
    state: started
    enabled: yes

- name: Keep root socket auth
  community.mysql.mysql_user:
    name: root
    host: localhost
    plugin: auth_socket
    state: present
    login_unix_socket: /var/run/mysqld/mysqld.sock

- name: Create root password login for automation
  community.mysql.mysql_user:
    name: root
    host: 127.0.0.1
    password: "{{ mysql_root_password }}"
    plugin: mysql_native_password
    priv: '*.*:ALL,GRANT'
    state: present
    login_unix_socket: /var/run/mysqld/mysqld.sock

- name: Remove all anonymous user accounts
  community.mysql.mysql_user:
    name: ''
    host_all: true
    state: absent
    login_user: root
    login_password: "{{ mysql_root_password }}"
    login_unix_socket: /var/run/mysqld/mysqld.sock

- name: Remove test database
  community.mysql.mysql_db:
    name: test
    state: absent
    login_user: root
    login_password: "{{ mysql_root_password }}"
    login_unix_socket: /var/run/mysqld/mysqld.sock