---
- name: Create jaeger-service group
  group:
    name: jaeger-service
    gid: 10001
    state: present

- name: Create jaeger-service system user
  user:
    name: jaeger-service
    uid: 10001
    group: jaeger-service
    system: true
    shell: /usr/sbin/nologin
    create_home: false
    comment: "Jaeger service user"
    state: present
