---
- name: Install NVIDIA drivers
  import_tasks: drivers.yml

- name: Install Docker and container components
  import_tasks: containers.yml

- name: Configure Open WebUI
  import_role:
    name: open_webui
