---
- name: restart docker
  systemd_service:
    name: docker
    state: restarted

- name: restart nginx
  systemd_service:
    name: nginx
    state: restarted

- name: restart chroma
  community.docker.docker_compose_v2:
    project_src: /opt/chroma/compose
    state: restarted
