---

- name: install packages for openvpn
  apt:
    - ca-certificates 
    - wget 
    - net-tools 
    - gnupg
  state: present

- name: Add OpenVPN GPG key
  ansible.builtin.get_url:
    url: https://as-repository.openvpn.net/as-repo-public.gpg
    dest: /etc/apt/trusted.gpg.d/as-repo-public.gpg.asc
    mode: '0644'
    force: true 

- name: Add OpenVPN repo
  ansible.builtin.apt_repository:
    filename: OpenVPN
    repo: 'deb [signed-by=/etc/apt/trusted.gpg.d/as-repo-public.gpg.asc] http://as-repository.openvpn.net/as/debian jammy main'

- name: update repos 
  apt:
    update_cache: yes     

- name: install OpenVPN package
  apt: 
    name: openvpn-as
    state: present 

