---
# main

- name: Install required packages
  import_tasks: packages.yml

- name: Add rabbitmq repository
  import_tasks: repo.yml

- name: Install rabbitmq
  import_tasks: install.yml

- name: Configure rabbitmq
  import_tasks: rabbitmq.yml

- name: Configure nginx proxy
  import_tasks: nginx.yml

- name: Install ssl certs
  import_tasks: ssl.yml
