---

# Remove in cleanup
#- name: Test GPU drivers
#  import_tasks: drivers.yml

- name: Install Docker and container components
  import_tasks: docker.yml
  
# everything listening on localhost
#- name: Start container services useing docker-compose
#  import_tasks: containers.yml

#- name: Configure Open WebUI inital admin account
#  import_tasks: openwebui.yml

#- name: Configure Nginx and SSL certificates
#  import_tasks: nginx.yml