---
# Main Rocket.Chat installation tasks

- name: Import Docker tasks
  import_tasks: docker.yml

- name: Import Rocket.Chat tasks
  import_tasks: container.yml

- name: Import Nginx tasks
  import_tasks: nginx.yml
