---
- name: create docker compose directory
  file:
    path: /etc/docker/compose/peppermint/
    state: directory

- name: create docker compose file
  template:
    src: docker-compose.yaml
    dest: "/etc/docker/compose/peppermint/docker-compose.yml"

- name: start peppermint containers with docker compose
  community.docker.docker_compose_v2:
    project_src: /etc/docker/compose/peppermint/
    state: present