---
# Install Addons if requested
- name: Add addons
  import_role:
    name: addons
  when: add_ons != ['none']

# motd and cred dump

- name: Copy MOTD template to /etc/motd
  template:
    src: templates/motd.j2
    dest: /etc/motd
    mode: '0600'
    owner: "{{ username }}"
    group: "{{ username }}"

- name: Writing deployment creds into file
  copy:
    dest: /home/{{ username }}/.credentials
    mode: '0600'
    owner: "{{ username }}"
    group: "{{ username }}"
    content: |
      Sudo Username: {{ username }}
      Sudo Password: {{ password }}
      Prometheus Username: prometheus
      Prometheus Password: {{ prometheus_htpasswd }}
      Grafana Username: admin
      Grafana Password: {{ grafana_password }}
      {% if install_loki | bool %}
      Loki Username: loki
      Loki Password: {{ loki_htpasswd }}
      {% endif %}
