---
- name: Set pritunl mongo uri
  shell: "pritunl set-mongodb mongodb://pritunl:{{ mongo_pritunl_password }}@127.0.0.1:27017/pritunl?authSource=pritunl"
  no_log: true

- name: Restarting pritunl to create the db for app
  systemd:
    name: pritunl
    state: restarted

- name: Set pritunl-web user to run the web service
  shell: pritunl set app.web_systemd true

- name: Get login creds
  shell: pritunl default-password
  register: pritunl_credentials
  no_log: true

- name: Restarting pritunl to pick up systemd change
  systemd:
    name: pritunl
    state: restarted
