---
- name: Add openvpn repository
  copy:
    dest: /etc/apt/sources.list.d/openvpn.list
    content: |
      deb [ signed-by=/usr/share/keyrings/openvpn-repo.gpg ] https://build.openvpn.net/debian/openvpn/stable noble main
    mode: '0644'

- name: Add pritunl repository
  copy:
    dest: /etc/apt/sources.list.d/pritunl.list
    content: |
      deb [ signed-by=/usr/share/keyrings/pritunl.gpg ] https://repo.pritunl.com/stable/apt noble main
    mode: '0644'

- name: Install gnupg
  apt:
    name: gnupg
    state: present

- name: Add openvpn gpg key
  get_url:
    url: https://swupdate.openvpn.net/repos/repo-public.gpg
    dest: /tmp/openvpn-repo.gpg
    mode: '0644'

- name: Decrypt and store openvpn gpg key
  shell: gpg --dearmor --yes -o /usr/share/keyrings/openvpn-repo.gpg /tmp/openvpn-repo.gpg

- name: Add pritunl gpg key
  get_url:
    url: https://raw.githubusercontent.com/pritunl/pgp/master/pritunl_repo_pub.asc
    dest: /tmp/pritunl_repo_pub.asc
    mode: '0644'

- name: Decrypt and store pritunl gpg key
  shell: gpg --dearmor --yes -o /usr/share/keyrings/pritunl.gpg /tmp/pritunl_repo_pub.asc

- name: Apt update
  apt:
    update_cache: true

- name: Install required packages
  apt:
    name: [pritunl, openvpn, wireguard, wireguard-tools]
    state: present

- name: Start and enable pritunl
  systemd:
    name: pritunl
    state: started
    enabled: true
