---
# Install Addons if requested
- name: Add addons
  import_role:
    name: addons
  when: add_ons != ['none']

# motd and cred dump

- name: Copy MOTD template to /etc/motd
  template:
    src: templates/motd.j2
    dest: /etc/motd

- name: Writing deployment creds into file
  copy:
    dest: /home/{{ username }}/.credentials
    mode: '0600'
    owner: "{{ username }}"
    group: "{{ username }}"
    content: |
      Sudo Username: {{ username }}
      Sudo Password: {{ password }}
      Valkey "default" User Password: {{ valkey_default_user_password }}
      {{ username }} Valkey User Password: {{ sudo_db_user_password }}
      Valkey CA Password (required to generate new certs): {{ ca_password }}
