---
- name: Install NVIDIA drivers
  import_tasks: drivers.yml

- name: Install Docker and container components
  import_tasks: containers.yml

- name: Configure Gemma 3 WebUI initial admin account
  import_tasks: gemma3.yml

- name: Configure Nginx and SSL certificates
  import_tasks: nginx.yml
