---
# install grafana

- name: Add grafana key
  get_url:
    url: 'https://apt.grafana.com/gpg.key'
    dest: '/usr/share/keyrings/grafana.key'
    mode: '0644'

- name: Add grafana repo
  apt_repository:
    repo: 'deb [signed-by=/usr/share/keyrings/grafana.key] https://apt.grafana.com stable main'
    state: present
    update_cache: true

- name: Install grafana
  apt:
    pkg: grafana
    state: present

- name: Update grafana config
  lineinfile:
    path: '/etc/grafana/grafana.ini'
    regex: '^\;admin_user = admin'
    line: admin_user = admin

- name: Update grafana password
  lineinfile:
    path: '/etc/grafana/grafana.ini'
    regex: '^\;admin_password = admin'
    line: 'admin_password = {{ grafana_password }}'

- name: Start and enable grafana
  systemd:
    name: grafana-server
    state: started
    enabled: true

- name: Run certbot
  import_role:
    name: certbot_ssl
