---
# grafana

- name: Install and configure nginx
  import_tasks: nginx.yml

- name: Install node_exporter
  import_role:
    name: data_exporter

- name: Install grafana
  import_tasks: grafana.yml
