---
## install nginx

- name: Install nginx pkgs
  apt:
    pkg: [nginx, apache2-utils]
    state: present

- name: Add nginx config
  template:
    src: 'templates/nginx.conf.j2'
    dest: '/etc/nginx/sites-available/{{ _domain }}'
    mode: '0644'

- name: Secure prometheus with htaccess
  community.general.htpasswd:
    path: '/etc/nginx/.prometheus_htpasswd'
    name: prometheus
    password: '{{ prometheus_htpasswd }}'
    state: present
    create: true
    mode: '0644'

- name: Secure loki with htaccess
  community.general.htpasswd:
    path: '/etc/nginx/.loki_htpasswd'
    name: loki
    password: '{{ loki_htpasswd }}'
    state: present
    create: true
    mode: '0644'
  when: install_loki | bool

- name: Enable grafana vhost
  file:
    src: '/etc/nginx/sites-available/{{ _domain }}'
    dest: '/etc/nginx/sites-enabled/{{ _domain }}'
    state: link

- name: Add connection upgrade to nginx config
  blockinfile:
    path: '/etc/nginx/nginx.conf'
    insertafter: '^http {'
    block: |2
              map $http_upgrade $connection_upgrade {
                 default upgrade;
                 '' close;
              }

- name: Remove default vhost
  file:
    path: '/etc/nginx/sites-enabled/default'
    state: absent
  notify: Restart nginx
