version: "3.1"

services:
  peppermint_postgres:
    container_name: peppermint_postgres
    image: postgres:latest
    restart: always
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql
    environment:
      POSTGRES_USER: peppermint
      POSTGRES_PASSWORD: "{{ postgres_password }}"
      POSTGRES_DB: peppermint

  peppermint:
    container_name: peppermint
    image: pepperlabs/peppermint:latest
    ports:
      - 3000:3000
      - 5003:5003
    restart: always
    depends_on:
      - peppermint_postgres
    healthcheck:
      test: ["CMD", "sh", "-c", "pgrep -f 'node' || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
    environment:
      DB_USERNAME: "peppermint"
      DB_PASSWORD: "{{ postgres_password }}"
      DB_HOST: "peppermint_postgres"
      SECRET: '{{ peppermint_secret }}'
      API_URL: "http://localhost:5003"

volumes:
 pgdata: