---
- name: Install NVIDIA drivers
  import_tasks: drivers.yml

- name: Install Docker and container components
  import_tasks: containers.yml

- name: Configure Open WebUI initial admin account
  import_tasks: gpt-oss.yml

- name: Configure Nginx and SSL certificates
  import_tasks: nginx.yml
